spring.application.name=demo

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.packages-to-scan=co.spring.rest.controller

spring.jpa.show-sql=true

spring.jwt.secret=${JWT_SECRET}
spring.jwt.expirationAccessTokenMinute=${EXPIRATION_ACCESS_TOKEN_MINUTE}
spring.jwt.expirationRefreshTokenMinute=${EXPIRATION_REFRESH_TOKEN_MINUTE}